/**
 * Intelligent Test Generator
 *
 * Takes TestScenario[] (produced by the scenario planner) and generates
 * complete Playwright test files. Each test includes:
 * - Proper setup (test.slow() for AI, waitForResponse for API-backed pages)
 * - Real input values derived from the app's data model
 * - Quality check assertions (relevance, completeness, citations, etc.)
 * - Reasoning comments explaining WHY each test exists
 *
 * Unlike the primitive generator which tests individual affordances,
 * this generates scenario-level tests that verify features work end-to-end.
 */

import type {
  TestScenario,
  Scenario,
  ScenarioStep,
  QualityCheck,
} from '../intelligence/types.js';

// ── Public API ─────────────────────────────────────────────

export interface IntelligentGenerateResult {
  totalFiles: number;
  totalTests: number;
  criticalTests: number;
  highTests: number;
  mediumTests: number;
  lowTests: number;
}

/**
 * Generate Playwright test files from intelligent test scenarios.
 * Returns a map of filename -> test file content.
 */
export function generateIntelligentTests(
  scenarios: TestScenario[],
): { files: Map<string, string>; result: IntelligentGenerateResult } {
  const files = new Map<string, string>();
  const result: IntelligentGenerateResult = {
    totalFiles: 0,
    totalTests: 0,
    criticalTests: 0,
    highTests: 0,
    mediumTests: 0,
    lowTests: 0,
  };

  for (const testScenario of scenarios) {
    if (testScenario.scenarios.length === 0) continue;

    const fileName = routeToFileName(testScenario.route);
    const testCode = generateTestFile(testScenario);
    files.set(fileName, testCode);
    result.totalFiles++;

    for (const s of testScenario.scenarios) {
      result.totalTests++;
      switch (s.priority) {
        case 'critical': result.criticalTests++; break;
        case 'high': result.highTests++; break;
        case 'medium': result.mediumTests++; break;
        case 'low': result.lowTests++; break;
      }
    }
  }

  return { files, result };
}

// ── File Generation ─────────────────────────────────────────

function generateTestFile(ts: TestScenario): string {
  const lines: string[] = [];

  // Header comment
  lines.push(`/**`);
  lines.push(` * ${ts.feature} — Intelligent E2E Tests`);
  lines.push(` *`);
  lines.push(` * Purpose: ${ts.purpose}`);
  lines.push(` * Route: ${ts.route}`);
  lines.push(` * Generated by UIC scenario planner (heuristic, no LLM)`);
  lines.push(` */`);
  lines.push(``);

  // Imports
  lines.push(`import { test, expect } from '@playwright/test';`);
  lines.push(``);

  // Determine if any scenario needs slow mode
  const hasAiScenarios = ts.scenarios.some((s) => s.timeout >= 15000);

  // Describe block
  lines.push(`test.describe('${escapeString(ts.feature)}', () => {`);

  // If all scenarios are AI-heavy, set slow at describe level
  if (hasAiScenarios && ts.scenarios.every((s) => s.timeout >= 15000)) {
    lines.push(`  test.slow();`);
    lines.push(``);
  }

  // Generate each test
  for (const scenario of ts.scenarios) {
    lines.push(generateSingleTest(scenario, ts.route, hasAiScenarios));
    lines.push(``);
  }

  lines.push(`});`);
  lines.push(``);

  return lines.join('\n');
}

// ── Single Test Generation ──────────────────────────────────

function generateSingleTest(
  scenario: Scenario,
  route: string,
  describeHasSlow: boolean,
): string {
  const lines: string[] = [];
  const indent = '    ';
  const isSlowTest = scenario.timeout >= 15000;

  // Reasoning comment
  lines.push(`  // ${scenario.reasoning.replace(/\n/g, '\n  // ')}`);
  lines.push(`  test('${escapeString(scenario.name)}', async ({ page }) => {`);

  // Slow flag for AI tests (only if not already set at describe level)
  if (isSlowTest && !describeHasSlow) {
    lines.push(`${indent}test.slow();`);
  }

  // Track whether we need to collect page text for assertions
  const needsTextCollection = scenario.qualityChecks.length > 0;
  let hasWaitedForContent = false;

  // Generate steps
  for (const step of scenario.steps) {
    const stepCode = generateStepCode(step, route, indent);
    lines.push(stepCode);

    if (step.action === 'wait') {
      hasWaitedForContent = true;
    }
  }

  // Generate quality check assertions
  if (needsTextCollection) {
    lines.push(``);
    lines.push(`${indent}// Quality checks`);

    // Collect page text for assertions
    if (!hasWaitedForContent) {
      lines.push(`${indent}await page.waitForTimeout(1000);`);
    }

    // For AI features, use expect.poll to wait for content
    if (isSlowTest) {
      lines.push(`${indent}const responseArea = page.locator('[class*="response"], [class*="answer"], [class*="message"], [class*="result"], [role="log"], main').last();`);
      lines.push(`${indent}const text = await expect.poll(async () => {`);
      lines.push(`${indent}  const t = await responseArea.textContent().catch(() => '');`);
      lines.push(`${indent}  return t || '';`);
      lines.push(`${indent}}, { timeout: ${scenario.timeout} }).not.toBe('');`);
      lines.push(`${indent}const pageText = await responseArea.textContent() || '';`);
    } else {
      lines.push(`${indent}const pageText = await page.locator('body').textContent() || '';`);
    }

    // Generate assertion code from quality checks
    for (const check of scenario.qualityChecks) {
      lines.push(generateQualityAssertion(check, indent));
    }
  }

  lines.push(`  });`);

  return lines.join('\n');
}

// ── Step Code Generation ────────────────────────────────────

function generateStepCode(step: ScenarioStep, route: string, indent: string): string {
  switch (step.action) {
    case 'goto': {
      const target = step.target || route;
      return `${indent}await page.goto('${escapeString(target)}');`;
    }

    case 'fill': {
      if (!step.target || !step.value) {
        return `${indent}// Skip fill: missing target or value`;
      }
      const locator = makeStepLocator(step);
      // For empty fills (edge case testing), just clear
      if (step.value === '') {
        return `${indent}await ${locator}.clear();`;
      }
      return `${indent}await ${locator}.fill('${escapeString(step.value)}');`;
    }

    case 'click': {
      if (!step.target) return `${indent}// Skip click: no target`;
      const locator = makeStepLocator(step);
      return `${indent}await ${locator}.first().click();`;
    }

    case 'press': {
      const key = step.target || 'Enter';
      return `${indent}await page.keyboard.press('${key}');`;
    }

    case 'wait': {
      const timeout = step.timeout || 3000;
      return `${indent}await page.waitForTimeout(${timeout});`;
    }

    case 'assert-visible': {
      if (!step.target) return `${indent}// Skip assert-visible: no target`;
      return `${indent}await expect(page.locator('${escapeString(step.target)}')).toBeVisible();`;
    }

    case 'assert-text': {
      if (!step.target || !step.value) return `${indent}// Skip assert-text: missing target or value`;
      return `${indent}await expect(page.locator('${escapeString(step.target)}')).toContainText('${escapeString(step.value)}');`;
    }

    case 'assert-url': {
      if (!step.value) return `${indent}// Skip assert-url: no value`;
      return `${indent}await expect(page).toHaveURL(/${escapeRegex(step.value)}/);`;
    }

    default:
      return `${indent}// Unknown step action: ${step.action}`;
  }
}

// ── Quality Check Assertions ────────────────────────────────

function generateQualityAssertion(check: QualityCheck, indent: string): string {
  const lines: string[] = [];
  lines.push(`${indent}// ${check.description}`);

  switch (check.type) {
    case 'relevance': {
      // Extract the regex pattern from the assertion string
      const match = check.assertion.match(/toMatch\(\/(.+?)\/([gimsu]*)\)/);
      if (match) {
        lines.push(`${indent}expect(pageText).toMatch(/${match[1]}/${match[2]});`);
      } else {
        lines.push(`${indent}${adaptAssertion(check.assertion)}`);
      }
      break;
    }

    case 'content-length': {
      const lengthMatch = check.assertion.match(/toBeGreaterThan\((\d+)\)/);
      const minLength = lengthMatch ? lengthMatch[1] : '50';
      lines.push(`${indent}expect(pageText.length).toBeGreaterThan(${minLength});`);
      break;
    }

    case 'citations': {
      const match = check.assertion.match(/toMatch\(\/(.+?)\/([gimsu]*)\)/);
      if (match) {
        lines.push(`${indent}expect(pageText).toMatch(/${match[1]}/${match[2]});`);
      } else {
        lines.push(`${indent}expect(pageText).toMatch(/source|citation|from:|subject:|reference|\\[\\d+\\]/i);`);
      }
      break;
    }

    case 'timing':
      // Timing is handled by test.slow() and timeout — no additional assertion needed
      lines.push(`${indent}// (timing enforced by test timeout)`);
      break;

    case 'no-error': {
      const match = check.assertion.match(/not\.toMatch\(\/(.+?)\/([gimsu]*)\)/);
      if (match) {
        lines.push(`${indent}expect(pageText).not.toMatch(/${match[1]}/${match[2]});`);
      } else {
        lines.push(`${indent}expect(pageText).not.toMatch(/error|exception|failed/i);`);
      }
      break;
    }

    case 'completeness': {
      lines.push(`${indent}expect(pageText.length).toBeGreaterThan(50);`);
      break;
    }

    default:
      lines.push(`${indent}${adaptAssertion(check.assertion)}`);
  }

  return lines.join('\n');
}

// ── Locator Helpers ─────────────────────────────────────────

/**
 * Build a Playwright locator from a scenario step's target.
 * Targets can be CSS selectors, comma-separated selectors, or
 * simple text patterns for clicking.
 */
function makeStepLocator(step: ScenarioStep): string {
  const target = step.target || '';

  // If target looks like a CSS selector (starts with valid selector chars)
  if (/^[.#\[a-z]/i.test(target) || target.includes('[') || target.includes(':has-text')) {
    // Multiple comma-separated selectors — use first matching
    if (target.includes(', ')) {
      const selectors = target.split(', ').map((s) => s.trim());
      // Use Playwright's or() chaining for reliability
      if (selectors.length <= 3) {
        const parts = selectors.map((s) => {
          if (s.includes(':has-text')) {
            // Convert :has-text to getByRole or getByText
            const textMatch = s.match(/:has-text\("(.+?)"\)/);
            if (textMatch) {
              const tagMatch = s.match(/^(\w+)/);
              if (tagMatch?.[1] === 'button') {
                return `page.getByRole('button', { name: /${escapeRegex(textMatch[1])}/i })`;
              }
              return `page.getByText(/${escapeRegex(textMatch[1])}/i)`;
            }
          }
          return `page.locator('${escapeString(s)}')`;
        });
        return parts.join('.or(') + ')'.repeat(parts.length - 1);
      }
      // Too many — just use the first one
      return `page.locator('${escapeString(selectors[0])}')`;
    }

    // Single :has-text selector
    if (target.includes(':has-text')) {
      const textMatch = target.match(/:has-text\("(.+?)"\)/);
      if (textMatch) {
        const tagMatch = target.match(/^(\w+)/);
        if (tagMatch?.[1] === 'button') {
          return `page.getByRole('button', { name: /${escapeRegex(textMatch[1])}/i })`;
        }
        return `page.getByText(/${escapeRegex(textMatch[1])}/i)`;
      }
    }

    return `page.locator('${escapeString(target)}')`;
  }

  // Target is a text label — try to click it by text
  if (target.length > 0 && target.length < 50) {
    return `page.getByText('${escapeString(target)}')`;
  }

  // Fallback
  return `page.locator('body')`;
}

// ── Utility Functions ───────────────────────────────────────

function routeToFileName(route: string): string {
  const name = route.replace(/^\//, '').replace(/\//g, '-').replace(/[^a-zA-Z0-9-]/g, '') || 'home';
  return `${name}.intelligent.spec.ts`;
}

function escapeString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Adapt a raw assertion string (from QualityCheck) to valid Playwright code.
 * Replaces `text` references with `pageText` for consistency.
 */
function adaptAssertion(assertion: string): string {
  return assertion.replace(/\btext\b(?!Content)/g, 'pageText');
}
